In [1]:
import numpy as np

In [2]:
array1 = np.array([(-4,17,-35), (74,-56,9), (11,7, -6)], dtype = int)   #Инициализация двух двумерных массивов
array2 = np.array([(23,8,-3), (-12,11,-2), (-1, 3, 2)], dtype = int)

In [3]:
array1, array2

(array([[ -4,  17, -35],
        [ 74, -56,   9],
        [ 11,   7,  -6]]),
 array([[ 23,   8,  -3],
        [-12,  11,  -2],
        [ -1,   3,   2]]))

In [4]:
# Инвентаризация одного из массивов (пусть это будет array1)

In [5]:
array1.shape           # Размерность массива

(3, 3)

In [6]:
array1.itemsize        # Вес элемента массива в байтах

4

In [7]:
array1.ndim            # Количество измерений массива

2

In [8]:
array1.size            # Количество элементов в массиве

9

In [9]:
array1.dtype.name      # Тип элементов в массиве

'int32'

In [10]:
# Алгебраические операции с массивами

In [11]:
np.exp(array1)                #Потенцирование каждого элемента массива array1

array([[1.83156389e-02, 2.41549528e+07, 6.30511676e-16],
       [1.37338298e+32, 4.78089288e-25, 8.10308393e+03],
       [5.98741417e+04, 1.09663316e+03, 2.47875218e-03]])

In [12]:
np.add(array1,array2)         #Сумма массивов

array([[ 19,  25, -38],
       [ 62, -45,   7],
       [ 10,  10,  -4]])

In [13]:
np.subtract(array1,array2)    #Разница массивов

array([[-27,   9, -32],
       [ 86, -67,  11],
       [ 12,   4,  -8]])

In [14]:
np.multiply(array1,array2)     #Умножение массивов

array([[ -92,  136,  105],
       [-888, -616,  -18],
       [ -11,   21,  -12]])

In [15]:
np.divide(array1,array2)       #Деление массивов

array([[ -0.17391304,   2.125     ,  11.66666667],
       [ -6.16666667,  -5.09090909,  -4.5       ],
       [-11.        ,   2.33333333,  -3.        ]])

In [16]:
# Сравнение массивов (return Boolean)

In [17]:
array1 == array2               #Поэлементное сравнение 

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [18]:
array1 < 0                     #Определение отрицательных элементов массива array1 

array([[ True, False,  True],
       [False,  True, False],
       [False, False,  True]])

In [19]:
np.array_equal(array1, array2)  #Cравнение "целиком"

False

In [20]:
# Функции агрегации

In [21]:
array1.min(), array1.max()    #Нахождение минимального и максимального элементов массива array1

(-56, 74)

In [22]:
array1.max(axis=0)            #Нахождение максимальных элементов в каждом столбце массива array1    

array([74, 17,  9])

In [23]:
array1.cumsum(axis=1)         #"Пошаговая" (кумулятивная) сумма элементов массива array1 по строкам

array([[ -4,  13, -22],
       [ 74,  18,  27],
       [ 11,  18,  12]], dtype=int32)

In [24]:
array1.mean()                 #Среднее арифметическое элементов массива array1 

1.8888888888888888

In [25]:
# Основные функции линейной алгебры с матрицами

In [26]:
from scipy import linalg, sparse
import cmath

In [27]:
ar1 = linalg.inv(array1)     #Инверсия элементов массива array1
ar1

array([[-0.00865266,  0.00453234,  0.05727235],
       [-0.01721023, -0.01296314,  0.08094831],
       [-0.03594181, -0.00681436,  0.03277234]])

In [28]:
ar1 = array1.transpose()     #Транспонирование массива array1
ar1

array([[ -4,  74,  11],
       [ 17, -56,   7],
       [-35,   9,  -6]])

In [29]:
np.linalg.matrix_rank(array1) #Определение ранга массива array1

3

In [30]:
linalg.det(array1)            #Определение детерминанта массива array1

-31550.999999999996

In [31]:
# Функции сортировки

In [32]:
array1.sort()                 #Сортировка по возрастанию элементов массива array1 построчно 
array1

array([[-35,  -4,  17],
       [-56,   9,  74],
       [ -6,   7,  11]])

In [33]:
array2.sort(axis=0)           #Сортировка по возрастанию элементов массива array2 по столбцам
array2

array([[-12,   3,  -3],
       [ -1,   8,  -2],
       [ 23,  11,   2]])